### ISSUE TITLE
Vraag over je bunq_pay repo

### ISSUE THREAD

**Issue by DaniWinter** [basst85/bunq_psd2_example#1]
Hoi!

Ik heb een vraag over je bunq_pay repo (die niet meer actief is, vandaar even via hier). 

Om 1 of andere reden werkt de “Openen in bunq app” actie met het bunq token (om te openen op dit apparaat i.p.v. via qr) niet. 

Ik krijg deze melding als ik de open in bunq actie aftrap. 
![20E33002-BB3A-4619-8286-93C02DBC69F6](https://user-images.githubusercontent.com/16963641/79364118-25b23e80-7f49-11ea-8a1c-e7f075223006.jpeg)

Als ik de QR scan vanaf een ander scherm kan ik wel gewoon de betaling starten. 

Het gaat hier trouwens om de bunq_pay via de bunq.me link methode. 

Enig idee waarom dit niet werkt?

Bedankt alvast!

Dani

**Comment by basst85** [comment]
> Hoi!
> 
> Ik heb een vraag over je bunq_pay repo (die niet meer actief is, vandaar even via hier).
> 
> Om 1 of andere reden werkt de “Openen in bunq app” actie met het bunq token (om te openen op dit apparaat i.p.v. via qr) niet.
> 
> Ik krijg deze melding als ik de open in bunq actie aftrap.
> ![20E33002-BB3A-4619-8286-93C02DBC69F6](https://user-images.githubusercontent.com/16963641/79364118-25b23e80-7f49-11ea-8a1c-e7f075223006.jpeg)
> 
> Als ik de QR scan vanaf een ander scherm kan ik wel gewoon de betaling starten.
> 
> Het gaat hier trouwens om de bunq_pay via de bunq.me link methode.
> 
> Enig idee waarom dit niet werkt?
> 
> Bedankt alvast!
> 
> Dani

Hi! 

Het lijkt erop dat de verkeerde link gegenereerd wordt vanuit de code.
De link moet beginnen met **bunq://x-bunq-app/token-qr-bunqme-fundraiser-profile-entry** i.p.v. bunq://x-bunq-app/token-qr-bunqme-tab-entry

Groeten,
Bastiaan

**Comment by basst85** [comment]
Ik verwacht dat dit ^ de fix is, daarom sluit ik dit issue :-)
