### ISSUE TITLE
Why deleted bunq pay?

### ISSUE THREAD

**Issue by payrequestio** [basst85/bunq_psd2_example#2]
Sorry to ask it here @basst85 but couldn't not contact you via other way.

**Comment by basst85** [comment]
Hi!

The example code was used on multiple scam sites.
I don’t want to help these scammers with their criminal activities.


Op di 21 apr. 2020 om 22:25 schreef PayRequest <notifications@github.com>

**Comment by payrequestio** [comment]
> Hi! The example code was used on multiple scam sites. I don’t want to help these scammers with their criminal activities. 

Good choice, i want to integrate Bunq in to https://payrequest.io  do you think there API is possible to let cusomters connect their Bunq and accept payments (ideal, creditcards) en redirect them back to their payment page?

**Comment by basst85** [comment]
> > Hi! The example code was used on multiple scam sites. I don’t want to help these scammers with their criminal activities.
> 
> Good choice, i want to integrate Bunq in to https://payrequest.io do you think there API is possible to let cusomters connect their Bunq and accept payments (ideal, creditcards) en redirect them back to their payment page?

@payrequestio You can contact me via Telegram: @Basst85
